# Generated by Django 3.1 on 2020-08-24 04:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_babybookentry_image_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babybookentry',
            name='entry',
            field=ckeditor.fields.RichTextField(blank=True, max_length=5000, null=True),
        ),
    ]
